# - Find crypto++
# Find the crypto++ includes and library
#
#  CRYPTOPP_INCLUDE_DIR - Where to find crypto++ include sub-directory.
#  CRYPTOPP_LIBRARIES   - List of libraries when using CRYPTOPP.
#  CRYPTOPP_FOUND       - True if CRYPTOPP found.
IF (CRYPTOPP_INCLUDE_DIR)
  # Already in cache, be silent.
  SET(CRYPTOPP_FIND_QUIETLY TRUE)
ENDIF (CRYPTOPP_INCLUDE_DIR)

set(CRYPTOPP_INCLUDE_DIR /usr/include)

SET(CRYPTOPP_NAMES crypto++)
FIND_LIBRARY(CRYPTOPP_LIBRARY NAMES ${CRYPTOPP_NAMES} )

# Handle the QUIETLY and REQUIRED arguments and set LIBRT_FOUND to
# TRUE if all listed variables are TRUE.
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(
	CRYPTOPP DEFAULT_MSG
	CRYPTOPP_LIBRARY CRYPTOPP_INCLUDE_DIR
)

IF(CRYPTOPP_FOUND)
	SET( CRYPTOPP_LIBRARIES ${CRYPTOPP_LIBRARY} )
ELSE(CRYPTOPP_FOUND)
	SET(CRYPTOPP_LIBRARIES )
ENDIF(CRYPTOPP_FOUND)

MARK_AS_ADVANCED( CRYPTOPP_LIBRARY CRYPTOPP_INCLUDE_DIR )
