if (NOT CMAKE_CXX_HIGHEST_STANDARD)
	include(CheckCXXCompilerFlag)

	CHECK_CXX_COMPILER_FLAG("-std=c++17" HAVE_CPP17_COMPILER)

	IF (HAVE_CPP17_COMPILER)
		set(CMAKE_CXX_HIGHEST_STANDARD
			17
			CACHE INTERNAL "Highest available C++ standard"
			FORCE
		)
	ELSE()
		set(CMAKE_CXX_HIGHEST_STANDARD
			14
			CACHE INTERNAL "Highest available C++ standard"
			FORCE
		)
	ENDIF()
endif()

if (CMAKE_CXX_HIGHEST_STANDARD EQUAL 14)
	set(CMAKE_CXX_STANDARD ${CMAKE_CXX_HIGHEST_STANDARD})
else()
	set(CMAKE_CXX_FLAGS "-std=c++${CMAKE_CXX_HIGHEST_STANDARD} ${CMAKE_CXX_FLAGS}")
endif()
set(CMAKE_C_STANDARD 11)